### ISSUE TITLE
Can't open usb storage via third party apps, and can't save screenshots

### ISSUE THREAD

**Issue by EricLin0509** [roddhjav/apparmor.d#412]
When I try to open files from my USB storage via third party apps such as VLC, Kdenlive, VSCode and so on, it shows no permission to the location. Here is the log:
```
apparmor="ALLOWED" operation="open" class="file" profile="totem" name="/run/media/Ericlin/E25B-42CB/"  comm="pool-totem" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="ALLOWED" operation="open" class="file" profile="totem" name="/run/mount/utab"  comm="pool-totem" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="Ericlin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="gvfs-udisks2-volume-monitor" name="/run/media/Ericlin/E25B-42CB/"  comm="gvfs-udisks2-vo" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="open" class="file" profile="vlc" name="/run/media/Ericlin/E25B-42CB/Young Kindaichi's Casebook TV001-148 Fin 1997 HDTVRip 1080p x264 AC3/"  comm="vlc" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="open" class="file" profile="gvfs-udisks2-volume-monitor" name="/run/media/Ericlin/E25B-42CB/"  comm="pool" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="open" class="file" profile="xdg-desktop-portal-gnome" name="/run/media/Ericlin/E25B-42CB/"  comm="pool-xdg-deskto" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="file_inherit" class="file" profile="nautilus" name="/dev/pts/0"  comm="nautilus" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="open" class="file" profile="xdg-desktop-portal-gnome" name="/etc/apparmor.d/abstractions/user-download"  comm="pool-xdg-deskto" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="Ericlin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="xdg-desktop-portal-gnome" name="/etc/apparmor.d/abstractions/apache2-common"  comm="pool-xdg-deskto" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="Ericlin" OUID="root"
apparmor="DENIED" operation="open" class="file" profile="gnome-shell" name="/run/user/1000/app/com.google.Chrome/.com.google.Chrome.6b2ZVj"  comm="pool-gnome-shel" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="file_lock" class="file" profile="unix-chkpwd" name="/dev/pts/0"  comm="sudo" requested_mask="k" denied_mask="k" fsuid=0 ouid=1000 FSUID="root" OUID="Ericlin"
```

And I noticed that if I take a screenshot, it won't save. Here is the log:
```
apparmor="DENIED" operation="mknod" class="file" profile="gnome-shell" name="/home/Ericlin/图片/截图/截图 2024-07-14 23-51-48.png"  comm="gnome-shell" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
apparmor="DENIED" operation="mknod" class="file" profile="gnome-shell" name="/home/Ericlin/图片/截图/截图 2024-07-14 23-52-41.png"  comm="gnome-shell" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000 FSUID="Ericlin" OUID="Ericlin"
```

**Comment by roddhjav** [comment]
Should be fixed now.

Regarding the screenshot, you need to set [`@{XDG_SCREENSHOTS_DIR}`](https://apparmor.pujol.io/configuration/#personal-directories) if it is different from the default one.

Same for vlc & totem, you need to add: `@{user_videos_dirs} += @{run}/media/@{user}/` (unless you move your video inside  @{run}/media/@{user}/@{XDG_VIDEO_DIR}`

**Comment by EricLin0509** [comment]
Now it can read files from USB storage, but I still can't take screenshots with configurations. I created a "local" file inside /etc/apparmor.d/tunables/xdg-user-dirs.d/apparmor.d.d/ , and added these code to the file:
`@{user_videos_dirs} += @{run}/media/@{user}/*
@{user_pkg_dirs}+=@{user_cache_dirs}/yay/
@{XDG_SCREENSHOTS_DIR} += "@{XDG_PICTURES_DIR}/截图/*"
@{XDG_PICTURES_DIR} += "图片"`
I tried to take a screenshot after restart the service, it didn't work, it got the same error
