### ISSUE TITLE
remmina won't launch when using remmina.desktop

### ISSUE THREAD

**Issue by inittux111** [roddhjav/apparmor.d#902]
Since a few updates I started noticing that remmina won't launch when using the remmina.desktop to launch. I removed "apparmor.d-git" and then remmina launches like normal when using remmina.desktop. I went searching in audit.log and with aursearch -r for specific things about remmina but can't find anything. When I follow the journal when launching remmina I see this.

```
Oct 11 13:42:48 anubis gnome-software[5054]: can't init metadata tree /home/maarten/.local/share/gvfs-metadata/root: open: Permission denied
```

If you let me know how to get more useful log lines for this I will provide those?

**Comment by JND94** [comment]
https://apparmor.pujol.io/report/

**Comment by inittux111** [comment]
@JND94 Thanks!

[aa-log.txt](https://github.com/user-attachments/files/22877594/aa-log.txt)

**Comment by roddhjav** [comment]
Thanks, this is massively helpful. It should be fixed now.

Note: You may also want to add `@{HOME}/Git/configs/dothome/@{HOME}/share/fonts/** r,` in the local addition of `/etc/apparmor.d/abstractions/icons`. You may have to do the same in the fonts abstraction... I cannot add them globally as these are your own dotfiles.

**Comment by inittux111** [comment]
@roddhjav Thanks! Is that done by creating a "/etc/apparmor.d/abstractions/icons.local" file with that line you shared in it or does it need to be under "/etc/apparmor.d/local/abstrations/icons"?

**Comment by inittux111** [comment]
> [@roddhjav](https://github.com/roddhjav) Thanks! Is that done by creating a "/etc/apparmor.d/abstractions/icons.local" file with that line you shared in it or does it need to be under "/etc/apparmor.d/local/abstrations/icons"?

Or is it done like this?
`All of these abstractions can be extended by a system admin by adding rules in a file under /etc/apparmor.d/<name>.d where <name> is the name of one of these abstractions.`
https://apparmor.pujol.io/development/abstractions

Which would mean I would need to create two files:
/etc/apparmor.d/icons.d/icons
/etc/apparmor.d/fonts.d/fonts

**Comment by inittux111** [comment]
> Thanks, this is massively helpful. It should be fixed now.

I don't see it was pushed to the main branch yet?

**Comment by roddhjav** [comment]
It is merged now.

> Which would mean I would need to create two files:
> /etc/apparmor.d/icons.d/icons
> /etc/apparmor.d/fonts.d/fonts

No, local additions in abstraction are in the abstraction directory. So `/etc/apparmor.d/abstractions/icons.d/icons`.
In case of doudbt, have a look at the abstraction, it ends by `include if exists <abstractions/icons.d>`, meaning it loads everything in `/etc/apparmor.d/abstractions/icons.d/`.

**Comment by inittux111** [comment]
@roddhjav Thanks!

I updated and rebooted and tried launching remmina again with remmina.desktop. It's still not launching
Here's the raw 

I generated more logs for you, one with  the raw logs and one where the profiles are generated.

[aa-log-raw.txt](https://github.com/user-attachments/files/22909459/aa-log-raw.txt)
[aa-log-prof.txt](https://github.com/user-attachments/files/22909432/aa-log-prof.txt)

In the one where it generated  a profile format from the aa-log I noticed it's still showing something about remmina.
```
profile remmina flags=(attach_disconnected) {
  apparmor/.null rw, # Failed name lookup - disconnected path
  systemd/journal/stdout rw, # file_inherit Failed name lookup - disconnected path
}
```

**Comment by roddhjav** [comment]
My bad, it should be fixed in #905

**Comment by inittux111** [comment]
Thanks, will wait for it to get merged and once it is will test it again.

**Comment by inittux111** [comment]
I'm still not able to open remmina. Here's my current log files.

[aa-log-prof.log](https://github.com/user-attachments/files/23027649/aa-log-prof.log)
[aa-log-raw.log](https://github.com/user-attachments/files/23027650/aa-log-raw.log)

**Comment by roddhjav** [comment]
Normal, the PR has not been merged yet.

**Comment by inittux111** [comment]
My bad. I had gotten an update so I thought it was merged.

**Comment by inittux111** [comment]
It works. Thanks!
